version: '3.8'

services:
  # Development service
  knowledge-portal-dev:
    image: node:18-alpine
    container_name: knowledge-portal-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8080
      - CI=false
      - DISABLE_ESLINT_PLUGIN=true
    command: sh -c "npm config set fetch-timeout 300000 && npm install && npm start"
    networks:
      - app-network

  # Production service
  knowledge-portal-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knowledge-portal-prod
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8000
    restart: unless-stopped
    networks:
      - app-network

  # Reverse proxy for development
  nginx-dev:
    image: nginx:alpine
    container_name: knowledge-portal-nginx-dev
    ports:
      - "8080:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - knowledge-portal-dev
    networks:
      - app-network

  # Standalone frontend build
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knowledge-portal-frontend
    ports:
      - "3002:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 


# cd knowledge_portal_backend
